# Generated by Django 4.2.5 on 2023-09-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/categories/'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
